GRANT USAGE ON SCHEMA bctw TO bctw_api;
GRANT USAGE ON SCHEMA bctw_dapi_v1 TO bctw_api;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON FUNCTION bctw.get_animal_collar_assignment_history(stridir text, animalid uuid) TO bctw_api;
GRANT ALL ON FUNCTION bctw.is_valid(valid_to timestamp without time zone) TO bctw_api;
GRANT ALL ON FUNCTION bctw.is_valid(valid_to timestamp with time zone) TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.animal_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.collar_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.alert_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.animal_historic_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.code_category_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.code_header_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.code_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.collar_animal_assignment_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.collar_historic_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.currently_attached_collars_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.currently_unattached_critters_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.onboarding_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.permission_requests_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.species_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.user_animal_assignment_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.user_v TO bctw_api;
GRANT ALL ON TABLE bctw_dapi_v1.vectronic_devices_without_keyx_entries TO bctw_api;
ALTER DEFAULT PRIVILEGES FOR ROLE bctw IN SCHEMA bctw_dapi_v1 REVOKE ALL ON TABLES  FROM bctw;
ALTER DEFAULT PRIVILEGES FOR ROLE bctw IN SCHEMA bctw_dapi_v1 GRANT ALL ON TABLES  TO bctw_api;